version: "3.4"

services:
  bomb1:
    build: .
    restart: always
    working_dir: "/bombcrypto-superbot"
    environment:
      LOGIN: "MUDAR"
      TELEGRAM_KEY: "MUDAR"
  bomb2:
    build: .
    restart: always
    working_dir: "/bombcrypto-superbot"
    environment:
      LOGIN: "MUDAR"
      TELEGRAM_KEY: "MUDAR"



